language: node_js
  - 9
  - 8
dist: trusty

sudo: false

addons:
  chrome: stable

install:
  - npm --version
  - npm i

script:
  - yarn test
  - yarn build

cache:
  directories:
    - node_modules
    