language: node_js
  - 9
  - 8
dist: trusty

# Work-around for https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
sudo: required

addons:
  chrome: stable

install:
  - npm --version
  - npm i

script:
  - yarn test
  - yarn build

cache:
  directories:
    - node_modules
